language: node_js
node_js:
  - "6"
  - "7"

python: 
  - "2.7"

services:
  - redis-server

before_install: 
  - make travis-install
  - make travis-run

env:
  - REDIS_HOST=localhost REDIS_PORT=6379
  - REDIS_CLUSTER_NODES=localhost:7000,localhost:7001,localhost:7002 
